#!/usr/bin/env ruby

$LOAD_PATH.unshift("./lib")

require "thor"
require "hammer"
require "hammer/cli"

class HammerCLI < Thor
  include Hammer
  include Hammer::CLI

  class_option :extras, type: :hash, default: {}
  # Options supported by extras:
  #  * worksheet_idx: the worrkbook sheet to analyze
  class_option :fullload, type: :boolean, default: false
  class_option :output, type: :string

  desc "inspect FILE", "Inspect a file and extract basic stats"
  option :stats, type: :boolean, default: false
  option :sample, type: :boolean, default: false
  alias :inspect_aliased :inspect

  desc "template FILE TEMPLATE", "Process the template in the file"
  alias :template_aliased :template

  desc "interactive", "Executes a interactive session"
  option :file, type: :string
  alias :interactive_aliased :interactive
end

HammerCLI.start(ARGV)
